version: "3.3"
services:
  user_service:
    build: ./user_service
    ports:
      - "5050:5050"
    volumes:
      - shared_data:/app/users
    environment:
      - DOCKER_ENV=true
    command: python /app/user.py
      

  file_service:
    build: ./file_service
    ports:
      - "5051:5051"
    volumes:
      - ./file_service/files:/app/files
      - shared_data:/app/users
    environment:
      - DOCKER_ENV=true
    command: python /app/file.py
    
volumes:
  shared_data:
